footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

###### layer definitions ######

# The static layer is in charge of providing the static map to the costmaps that require it (global costmap)
static:
    # The topic that the costmap subscribes to for the static map
    map_topic: /map
    subscribe_to_updates: true

# The obstacle layer is in charge of the marking and clearing operations
# marking:  insert obstacle information into the costmap
# clearing: remove obstacle information from the costmap
obstacles_laser:
    # A list of observation source names separated by spaces. This defines each of the source_name namespaces defined below
    observation_sources: laser
    # /source_name/topic (default: source_name): The topic on which sensor data comes in for this source. Defaults to the name of the source.
    # /source_name/data_type (default: "PointCloud"): The data type associated with the topic, right now only "PointCloud," "PointCloud2," and "LaserScan" are supported.
    # /source_name/clearing (default: false): Whether or not this observation should be used to clear out freespace.
    # /source_name/marking (default: true): Whether or not this observation should be used to mark obstacles.
    # /source_name/inf_is_valid (default: false): Allows for Inf values in "LaserScan" observation messages. The Inf values are converted to the laser's maximum range.
    # /source_name/max_obstacle_height (default: 2.0): The maximum height of any obstacle to be inserted into the costmap, in meters. This parameter should be set to be slightly higher than the height of your robot.
    # /source_name/obstacle range (default: 2.5): The default maximum distance from the robot at which an obstacle will be inserted into the cost map, in meters. This can be overridden on a per-sensor basis.
    # /source_name/raytrace_range (default: 3.0): The default range in meters at which to raytrace out obstacles from the map using sensor data. This can be overridden on a per-sensor basis.
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, obstacle_range: 0.2}

# The inflation layer is in charge of performing inflation in each cell with an obstacle
inflation:
    # The radius in meters to which the map inflates obstacle cost values
    inflation_radius: 0.2
    # A scaling factor to apply to cost values during inflation
    cost_scaling_factor: 10